c1=int(input("Enter the a: "))
c2=int(input("Enter the b: "))
match(int(input("Enter your choice first: "))):
    case 1: print("Addition: ",c1+c2)
    case 2: print("Subtraction: ",c1-c2)
    case 3: print("Multiplication: ",c1*c2)
    case 4: print("Division: ",c1/c2)
    case 5: print("modulo: ",c1%c2)
    case 6: print("Exponentiation: ",c1**c2)
    case 7: print("Floor Division: ",c1//c2)
    case 8: print("Bitwise AND: ",c1&c2)
    case 9: print("Bitwise OR: ",c1|c2)
    case 10: print("Bitwise XOR: ",c1^c2)
    case _: print("Invalid choice")